services:
  kernalyse:
    build:
      context: .
      dockerfile: Dockerfile
    image: kernalyse-nsys
    container_name: kernalyse
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: python3 app/app.py
